config/routes.rb
Rails.application.routes.draw do
  resources :launches
  resources :next_launch

  root 'next_launch#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/launches_controller.rb
class LaunchesController < ApplicationController
  def index
    @launches = api_client.all_launches(:limit => 10).reverse
  end

  def show
    @launch = api_client.one_launch(params[:id])
  end

  private
  def launch_params
    params.require(:id).permit!
  end

  def api_client
    @client ||= SpacexApi::V3::Client.new
  end
end

app/controllers/next_launch_controller.rb
class NextLaunchController < ApplicationController
  def index
    @launch = api_client.next_launch
  end

  private

  def api_client
    @client ||= SpacexApi::V3::Client.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/next_launch_helper.rb
module NextLaunchHelper
  def time_until_launch(launch_time)
    launch_datetime = launch_time.to_datetime
    TimeDifference.between(DateTime.current, launch_datetime).humanize
  end

  def formatted_launch_time(launch_time)
    launch_time.to_datetime.strftime("%R %A, %d of %B %Y")
  end
end

app/views/launches/index.html.erb
<% @launches.each do |launch| %>
  <div class="container">
    <h1><%= link_to launch["mission_name"], launch_path(launch["flight_number"]) %></h1>
    <h2>Launched on: <%= launch["launch_date_utc"] %></h2>
    <h3>Rocket: <%= launch["rocket"]["rocket_name"] %></h3>
    <h3>Launch Site: <%= launch["launch_site"]["site_name_long"] %>
    <% if launch["launch_success"] %>
      <p>Launch Succeeded</p>
    <% else %>
      <p> Launch Failed</p>
    <% end %>
    <p><%= launch["details"] %></p>
  </div>
  <% end %>

app/views/launches/show.html.erb
<div class="container">
  <h1><%= @launch["mission_name"] %></h1>
  <h2>Launched on: <%= @launch["launch_date_utc"] %></h2>
  <h3>Details: <%= @launch["details"] %></h3>
  <a href=<%= @launch["telemetry"]["flight_club"] %>>Telemetry Data</a>
  <h3> Launch Site: <%= @launch["launch_site"]["site_name_long"] %></h3>
  <div class="time-line">
    <ul>Time Line</ul>
      <% @launch["timeline"].each do |key, value| %>
        <li><%= key %>: <%= value %></li>
      <% end %>
    </ul>
  </div>  
  <ul>Links: </ul>
  <% @launch["links"].each do |key, value| %>
    <li><a href="<%= value %>"><%= key %></a></li>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<header>
  <%= link_to 'Launches', launches_path %>
  <div id="header-title"><h1>SpaceXplorer</h1></div>
  <%= link_to 'Next Launch', next_launch_index_path %>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spacexplorer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/next_launch/index.html.erb
<div class="container">
<h1>Next SpaceX launch <%= formatted_launch_time(@launch["launch_date_local"]) %></h1>
<h2><%= time_until_launch(@launch["launch_date_local"]) %> until launch.</h2>
<h2><%= @launch["mission_name"] %></h2>
<h2>Rocket: <%= @launch["rocket"]["rocket_name"] %></h2>
<h2>First Stage: <% @launch["rocket"]["first_stage"]["cores"].each do |core| %></h2>
  <p>Core serial: <%= core["core_serial"] %></p>
  <p>Intent to land?: <%= core["landing_intent"] %></p>
<% end %>
<h2>Second Stage/Payload: <% @launch["rocket"]["second_stage"]["payloads"].each do |payload| %></h2>
  <p><%= payload["payload_id"] %></p>
  <p>Customer: <%= payload["customers"].first %></p>
  <p>Payload type: <%= payload["payload_type"] %></p>
  <p>Payload mass: <%= payload["payload_mass_kg"] %> Kgs</p>
<% end %>
</div>